/*TEN CHUONG TRINH
COPYRIGHT BY XUAN KIEN*/
//DINH NGHIA VA TICH HOP CAC THU VIEN CAN THIET
#ifndef __MAIN_H
#define __MAIN_H

#include<htc.h>
#include<math.h>//chen thu vien chua cac ham can su dung
#include<stdlib.h>
#include<stdio.h>
#include"lcd.h"
#include"PWM.H"
//#include"TIMER.H"
//#include"ISR.H"

/***************************************************************/
//cau hinh su dung dao dong thach anh 4M
//__CONFIG(HS & WDTDIS & PWRTEN & UNPROTECT & BORDIS & LVPDIS);
#define _XTAL_FREQ 4000000

#endif